### ISSUE TITLE
`Pulumi.Tls` depends on alpha version of `Pulumi` dotnet nuget package

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi-tls#119]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
[`Pulumi.Tls`](https://www.nuget.org/packages/Pulumi.Tls/4.2.0) version `4.2.0` depends on _alpha_ version (`3.29.0-alpha.1649268066`) of [`Pulumi`](https://www.nuget.org/packages/Pulumi) dotnet nuget package. This [breaks](https://github.com/gitfool/Pulumi.Dungeon/runs/5862745644?check_suite_focus=true#step:8:278) builds until the next stable `Pulumi` package is published:
```
  /__w/Pulumi.Dungeon/Pulumi.Dungeon/Aws/Aws.csproj : error NU1605: Detected package downgrade: Pulumi from 3.29.0-alpha.1649268066 to 3.28.0. Reference the package directly from the project to select a different version.  [/__w/Pulumi.Dungeon/Pulumi.Dungeon/Pulumi.Dungeon.sln]
  /__w/Pulumi.Dungeon/Pulumi.Dungeon/Aws/Aws.csproj : error NU1605:  Aws -> Pulumi.Tls 4.2.0 -> Pulumi (>= 3.29.0-alpha.1649268066)  [/__w/Pulumi.Dungeon/Pulumi.Dungeon/Pulumi.Dungeon.sln]
  /__w/Pulumi.Dungeon/Pulumi.Dungeon/Aws/Aws.csproj : error NU1605:  Aws -> Pulumi (>= 3.28.0) [/__w/Pulumi.Dungeon/Pulumi.Dungeon/Pulumi.Dungeon.sln]
  /__w/Pulumi.Dungeon/Pulumi.Dungeon/Cli/Cli.csproj : error NU1605: Detected package downgrade: Pulumi from 3.29.0-alpha.1649268066 to 3.28.0. Reference the package directly from the project to select a different version.  [/__w/Pulumi.Dungeon/Pulumi.Dungeon/Pulumi.Dungeon.sln]
  /__w/Pulumi.Dungeon/Pulumi.Dungeon/Cli/Cli.csproj : error NU1605:  pulumi-dungeon -> Aws -> Pulumi.Tls 4.2.0 -> Pulumi (>= 3.29.0-alpha.1649268066)  [/__w/Pulumi.Dungeon/Pulumi.Dungeon/Pulumi.Dungeon.sln]
  /__w/Pulumi.Dungeon/Pulumi.Dungeon/Cli/Cli.csproj : error NU1605:  pulumi-dungeon -> Aws -> Pulumi (>= 3.28.0) [/__w/Pulumi.Dungeon/Pulumi.Dungeon/Pulumi.Dungeon.sln]
      0 Warning(s)
      2 Error(s)
```

### Steps to reproduce

1. Upgrade to latest `Pulumi.Tls` package
2. Build breaks

Expected: 🚀 
Actual: 💥

**Comment by jkodroff** [comment]
@gitfool Thanks for pointing this out. I submitted a PR to fix the issue: #127. We'll release a new version of the provider once this is merged.
