### ISSUE TITLE
Latest Python SDK has duplicate ID property in CertRequest get method which throws error using library

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-tls#120]
## Issue details

Cannot use the latest version in Python as the CertRequest get method has a duplicated ID property.
https://github.com/pulumi/pulumi-tls/blob/master/sdk/python/pulumi_tls/cert_request.py#L396

### Steps to reproduce

1. Install the latest version 4.2.0
2. Loading CertRequest throws import error do to bad code

Expected: Able to use CertRequest
Actual: Throws Python error `SyntaxError: duplicate argument 'id' in function definition`

**Comment by jkodroff** [comment]
@mitchellmaler Thanks for submitting this issue. When pulumi/pulumi-terraform-bridge#504 is complete, we will be able to fix the problem and will release a new version of the provider.

**Comment by stack72** [comment]
Closed via #123 

Sorry for the problem here @mitchellmaler
