### ISSUE TITLE
OriginCaCertificate references invalid TLS CertRequest Property `Subjects`

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-tls#498]
### What happened?

The example for [OriginCaCertificate](https://www.pulumi.com/registry/packages/cloudflare/api-docs/origincacertificate) references an invalid TLS CertRequest property `Subjects` whereas the property is `Subject`. 

### Example

Example in the registry
```
var exampleCertRequest = new Tls.CertRequest("exampleCertRequest", new()
    {
        PrivateKeyPem = examplePrivateKey.PrivateKeyPem,
        Subjects = new[]
        {
            new Tls.Inputs.CertRequestSubjectArgs
            {
                CommonName = "",
                Organization = "Terraform Test",
            },
        },
    });
```

Working example (c#)
```
var exampleCertRequest = new Tls.CertRequest("exampleCertRequest", new()
    {
        PrivateKeyPem = examplePrivateKey.PrivateKeyPem,
        Subject = new Tls.Inputs.CertRequestSubjectArgs
        {
            CommonName = "example.com",
            Organization = "ACME Examples, Inc",
        },
    });
```

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by phillipedwards** [comment]
Also!!!! the broken examples references Terraform :/

**Comment by iwahbe** [comment]
Hey @phillipedwards. Both issues have since been fixed, but we haven't had a release to publish them. I'll kick off a patch release now.
