### ISSUE TITLE
no resource plugin tls-v2.4.0 found in the workspace or on your $PATH

### ISSUE THREAD

**Issue by iridian-ks** [pulumi/pulumi-tls#64]
Not sure if this bug belongs here or in a different pulumi project.

I updated Pulumi and all plugins and Python dependencies to the latest versions. After doing that I'm now getting an error that the tls plugin isn't on version 2.4.0.. which obviously doesn't exist since it looks like 2.3.0 is the latest.

```
     └─ pulumi:providers:tls                                    default_2_4_0                                   1 error

Diagnostics:
  pulumi:providers:tls (default_2_4_0):
    error: no resource plugin 'tls-v2.4.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource tls v2.4.0`
```

It seems I have the correct version installed:

```
# ls /usr/local/lib/python3.7/site-packages/ | grep pulumi_tls
pulumi_tls
pulumi_tls-2.3.0.dist-info
```

```
# pulumi version; ls -w 1 /root/.pulumi/plugins/
v2.10.0
resource-aws-v2.11.0
resource-aws-v2.13.1
resource-consul-v2.2.1
resource-consul-v2.3.0
resource-docker-v2.2.3
resource-f5bigip-v2.3.0
resource-kubernetes-v2.3.1
resource-kubernetes-v2.4.0
resource-kubernetes-v2.4.3
resource-kubernetes-v2.5.0
resource-rancher2-v2.2.0
resource-random-v2.1.3
resource-random-v2.3.0
resource-random-v2.3.1
resource-terraform-v2.3.0
resource-tls-v2.1.3
resource-tls-v2.2.0
resource-tls-v2.3.0
resource-vault-v2.2.1
```

**Comment by stack72** [comment]
Hi @iridian-ks 

Are you saying that when you updated an existing plugin that it tried to install pulumi-tls 2.4.0?

Paul

**Comment by iridian-ks** [comment]
@stack72 no, I am running `pulumi up` and it's failing because `tls-v2.4.0` is not installed.

**Comment by stack72** [comment]
But it occurred when you upgraded the versions of the providers?

**Comment by iridian-ks** [comment]
The error message occurred when I ran `pulumi up`, but yes the error only started after upgrading both Pulumi from 2.9.0 to 2.10.0 as well as upgrading all of the providers to their latest versions.

I just tested trying to downgrade the pulumi_tls package as well as Pulumi back to their original versions, but I'm getting the same error. I do have other providers installed that I did not test downgrading back to their original versions.

**Comment by iridian-ks** [comment]
It seems to resolve if I do this:

```
tls_provider=tls.Provider("my-tls-provider")
tls_opts=pulumi.ResourceOptions(provider=tls_provider)
tls.PrivateKey(
  ...
  opts = tls_opts,
)
```

It seems the issue is when not feeding an explicit provider. Is this expected?

**Comment by iridian-ks** [comment]
I'm running Pulumi through Docker and I was able to find the previous docker image with the old working versions of the providers and Pulumi. I can reproduce by rebuilding the image, but in order to get work done, I'm stuck on this old image.

**Comment by jkodroff** [comment]
Closing: pulumi-tls is at 4.x at this point, so marking won't fix.
