### ISSUE TITLE
allowedUses documentation is incomplete

### ISSUE THREAD

**Issue by NickLarsenNZ** [pulumi/pulumi-tls#95]
It looks like perhaps a copy/paste issue, but the docs don't show the promised list of `allowedUses`.

https://github.com/pulumi/pulumi-tls/blob/0f8f089e90fa8edfc6416a7605498f957a22c337/sdk/nodejs/selfSignedCert.ts#L251-L255

To make it easier with language servers/intellisense, instead of being a `string`, could it be a type including common usage variants and fallback to a string?

eg:

```ts
type KeyUsage = "digitalSignature" | "keyEncipherment" | ... | string;
readonly allowedUses: pulumi.Input<pulumi.Input<KeyUsage>[]>; 
```

**Comment by NickLarsenNZ** [comment]
The closest I've come to finding possible values of `allowedUses` is:
https://gist.github.com/EronWright/81d0d016f4fb766074d59e863f132c67#file-ca-certificate-ts-L33-L37

**Comment by rafalkrupinski** [comment]
https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/self_signed_cert

**Comment by stack72** [comment]
We can close this out - we now have better documentation around this 

https://www.pulumi.com/registry/packages/tls/api-docs/selfsignedcert/#alloweduses_nodejs
